# The URL the site will be built for
base_url = "https://001-exemplo-zola.netlify.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"
description = "Meu blog Maravilhoso"
title = "Meu Blog"


[extra]
# Put all your custom variables here
hyde_links = [
    {url = "https://codeshow.com.br", name = "Codeshow"},
    {url = "https://youtube.com/codeshowbr", name = "Youtube"},
    {url = "/about", name = "Sobre Este Blog"},
]
hyde_theme = "theme-base-0d"
